In [1]:
import numpy as np

dim = 3
matris = np.array([
    [2,3,0,15],
    [1,2,1,13],
    [1,0,2,11]
],dtype='float32')

class GaussJordan():
    @staticmethod
    def echelon(arr):
        for col in range(dim): 
            for row in range(col+1,dim): 
                if arr[col][col] == 0: 
                    break 
                elim_ratio = arr[row][col] / arr[col][col]  
              
                arr[row] = arr[row] - elim_ratio * arr[col]
    @staticmethod
    def reducedEchelon(arr):
        GaussJordan.echelon(arr) 
        print(arr)
        for col in reversed(range(dim)):
            for row in reversed(range(col)): 
                if arr[col][col] == 0:
                    break 
                elim_ratio = arr[row][col] / arr[col][col] 
                arr[row] = arr[row] - elim_ratio * arr[col] 

    @staticmethod
    def solveSystem(arr):
        GaussJordan.reducedEchelon(arr)
        for idx, row in enumerate(arr): 
            yield row[-1]/row[idx]  

                

In [2]:
GaussJordan.echelon(matris)
print(matris)

[[  2.    3.    0.   15. ]
 [  0.    0.5   1.    5.5]
 [  0.    0.    5.   20. ]]


In [3]:
GaussJordan.reducedEchelon(matris)
print(matris)

for val in GaussJordan.solveSystem(matris):
    print(val)

[[  2.    3.    0.   15. ]
 [  0.    0.5   1.    5.5]
 [  0.    0.    5.   20. ]]
[[  2.    0.    0.    6. ]
 [  0.    0.5   0.    1.5]
 [  0.    0.    5.   20. ]]
[[  2.    0.    0.    6. ]
 [  0.    0.5   0.    1.5]
 [  0.    0.    5.   20. ]]
3.0
3.0
4.0
